# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 91b9fe9d954bd238c0a5e25446b68bf4ad570d219a45b82512e141c6aa7b53575e2dcaa94b6ea120e8a3b022868cb404e45619700421ccfc75eff44c094b9439

test:
  secret_key_base: 78de96b2515910a851b9ab1c1920387faa95f2a8da5d967b1a3d07070292238013fb11d9276268e20e08872e078a473bec03ecfbca260d5546edbb1ae69f17c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
